/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-23-2014
 * 
 * XDoclet definition:
 * @struts.form name="examinationForm"
 */
public class ExaminationForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** subjectName property */
	private String subjectName;

	/** examRequest property */
	private String examRequest;

	/** examTime property */
	private String examTime;

	/** examType property */
	private String examType;

	/** examName property */
	private String examName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the subjectName.
	 * @return String
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/** 
	 * Set the subjectName.
	 * @param subjectName The subjectName to set
	 */
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	/** 
	 * Returns the examRequest.
	 * @return String
	 */
	public String getExamRequest() {
		return examRequest;
	}

	/** 
	 * Set the examRequest.
	 * @param examRequest The examRequest to set
	 */
	public void setExamRequest(String examRequest) {
		this.examRequest = examRequest;
	}

	/** 
	 * Returns the examTime.
	 * @return String
	 */
	public String getExamTime() {
		return examTime;
	}

	/** 
	 * Set the examTime.
	 * @param examTime The examTime to set
	 */
	public void setExamTime(String examTime) {
		this.examTime = examTime;
	}

	/** 
	 * Returns the examType.
	 * @return String
	 */
	public String getExamType() {
		return examType;
	}

	/** 
	 * Set the examType.
	 * @param examType The examType to set
	 */
	public void setExamType(String examType) {
		this.examType = examType;
	}

	/** 
	 * Returns the examName.
	 * @return String
	 */
	public String getExamName() {
		return examName;
	}

	/** 
	 * Set the examName.
	 * @param examName The examName to set
	 */
	public void setExamName(String examName) {
		this.examName = examName;
	}
}