/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-20-2014
 * 
 * XDoclet definition:
 * @struts.form name="materialAnalysisForm"
 */
public class MaterialAnalysisForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** materialImage property */
//	private String materialImage;

	/** remark property */
	private String remark;

	/** sectionName property */
	private String sectionName;

	/** material property */
	private String material;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the materialImage.
	 * @return String
	 */
	//public String getMaterialImage() {
	//	return materialImage;
	//}

	/** 
	 * Set the materialImage.
	 * @param materialImage The materialImage to set
	 */
	//public void setMaterialImage(String materialImage) {
	//	this.materialImage = materialImage;
	//}

	/** 
	 * Returns the remark.
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/** 
	 * Set the remark.
	 * @param remark The remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/** 
	 * Returns the sectionName.
	 * @return String
	 */
	public String getSectionName() {
		return sectionName;
	}

	/** 
	 * Set the sectionName.
	 * @param sectionName The sectionName to set
	 */
	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	/** 
	 * Returns the material.
	 * @return String
	 */
	public String getMaterial() {
		return material;
	}

	/** 
	 * Set the material.
	 * @param material The material to set
	 */
	public void setMaterial(String material) {
		this.material = material;
	}
}