/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-17-2014
 * 
 * XDoclet definition:
 * @struts.form name="multiChoiceForm"
 */
public class MultiChoiceForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** optionD property */
	private String optionD;

	/** optionC property */
	private String optionC;

	/** optionB property */
	private String optionB;

	/** optionA property */
	private String optionA;

	/** remark property */
	private String remark;

	/** sectionName property */
	private String sectionName;

	/** analysis property */
	private String analysis;

	/** subjectName property */
	private String subjectName;

	/** answerF property */
	private String answerF;

	/** answerD property */
	private String answerD;

	/** answerE property */
	private String answerE;

	/** answerB property */
	private String answerB;

	/** questionStem property */
	private String questionStem;

	/** answerC property */
	private String answerC;

	/** answerA property */
	private String answerA;

	/** optionE property */
	private String optionE;

	/** optionF property */
	private String optionF;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the optionD.
	 * @return String
	 */
	public String getOptionD() {
		return optionD;
	}

	/** 
	 * Set the optionD.
	 * @param optionD The optionD to set
	 */
	public void setOptionD(String optionD) {
		this.optionD = optionD;
	}

	/** 
	 * Returns the optionC.
	 * @return String
	 */
	public String getOptionC() {
		return optionC;
	}

	/** 
	 * Set the optionC.
	 * @param optionC The optionC to set
	 */
	public void setOptionC(String optionC) {
		this.optionC = optionC;
	}

	/** 
	 * Returns the optionB.
	 * @return String
	 */
	public String getOptionB() {
		return optionB;
	}

	/** 
	 * Set the optionB.
	 * @param optionB The optionB to set
	 */
	public void setOptionB(String optionB) {
		this.optionB = optionB;
	}

	/** 
	 * Returns the optionA.
	 * @return String
	 */
	public String getOptionA() {
		return optionA;
	}

	/** 
	 * Set the optionA.
	 * @param optionA The optionA to set
	 */
	public void setOptionA(String optionA) {
		this.optionA = optionA;
	}

	/** 
	 * Returns the remark.
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/** 
	 * Set the remark.
	 * @param remark The remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/** 
	 * Returns the sectionName.
	 * @return String
	 */
	public String getSectionName() {
		return sectionName;
	}

	/** 
	 * Set the sectionName.
	 * @param sectionName The sectionName to set
	 */
	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	/** 
	 * Returns the analysis.
	 * @return String
	 */
	public String getAnalysis() {
		return analysis;
	}

	/** 
	 * Set the analysis.
	 * @param analysis The analysis to set
	 */
	public void setAnalysis(String analysis) {
		this.analysis = analysis;
	}

	/** 
	 * Returns the subjectName.
	 * @return String
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/** 
	 * Set the subjectName.
	 * @param subjectName The subjectName to set
	 */
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	/** 
	 * Returns the answerF.
	 * @return String
	 */
	public String getAnswerF() {
		return answerF;
	}

	/** 
	 * Set the answerF.
	 * @param answerF The answerF to set
	 */
	public void setAnswerF(String answerF) {
		this.answerF = answerF;
	}

	/** 
	 * Returns the answerD.
	 * @return String
	 */
	public String getAnswerD() {
		return answerD;
	}

	/** 
	 * Set the answerD.
	 * @param answerD The answerD to set
	 */
	public void setAnswerD(String answerD) {
		this.answerD = answerD;
	}

	/** 
	 * Returns the answerE.
	 * @return String
	 */
	public String getAnswerE() {
		return answerE;
	}

	/** 
	 * Set the answerE.
	 * @param answerE The answerE to set
	 */
	public void setAnswerE(String answerE) {
		this.answerE = answerE;
	}

	/** 
	 * Returns the answerB.
	 * @return String
	 */
	public String getAnswerB() {
		return answerB;
	}

	/** 
	 * Set the answerB.
	 * @param answerB The answerB to set
	 */
	public void setAnswerB(String answerB) {
		this.answerB = answerB;
	}

	/** 
	 * Returns the questionStem.
	 * @return String
	 */
	public String getQuestionStem() {
		return questionStem;
	}

	/** 
	 * Set the questionStem.
	 * @param questionStem The questionStem to set
	 */
	public void setQuestionStem(String questionStem) {
		this.questionStem = questionStem;
	}

	/** 
	 * Returns the answerC.
	 * @return String
	 */
	public String getAnswerC() {
		return answerC;
	}

	/** 
	 * Set the answerC.
	 * @param answerC The answerC to set
	 */
	public void setAnswerC(String answerC) {
		this.answerC = answerC;
	}

	/** 
	 * Returns the answerA.
	 * @return String
	 */
	public String getAnswerA() {
		return answerA;
	}

	/** 
	 * Set the answerA.
	 * @param answerA The answerA to set
	 */
	public void setAnswerA(String answerA) {
		this.answerA = answerA;
	}

	/** 
	 * Returns the optionE.
	 * @return String
	 */
	public String getOptionE() {
		return optionE;
	}

	/** 
	 * Set the optionE.
	 * @param optionE The optionE to set
	 */
	public void setOptionE(String optionE) {
		this.optionE = optionE;
	}

	/** 
	 * Returns the optionF.
	 * @return String
	 */
	public String getOptionF() {
		return optionF;
	}

	/** 
	 * Set the optionF.
	 * @param optionF The optionF to set
	 */
	public void setOptionF(String optionF) {
		this.optionF = optionF;
	}
}