/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-15-2014
 * 
 * XDoclet definition:
 * @struts.form name="singleChoiceForm"
 */
public class SingleChoiceForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** optionD property */
	private String optionD;

	/** optionC property */
	private String optionC;

	/** optionB property */
	private String optionB;

	/** subjectName property */
	private String subjectName;

	/** optionA property */
	private String optionA;

	/** answer property */
	private String answer;

	/** sectionName property */
	private String sectionName;

	/** questionStem property */
	private String questionStem;

	/** analysis property */
	private String analysis;

	/** optionE property */
	private String optionE;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the optionD.
	 * @return String
	 */
	public String getOptionD() {
		return optionD;
	}

	/** 
	 * Set the optionD.
	 * @param optionD The optionD to set
	 */
	public void setOptionD(String optionD) {
		this.optionD = optionD;
	}

	/** 
	 * Returns the optionC.
	 * @return String
	 */
	public String getOptionC() {
		return optionC;
	}

	/** 
	 * Set the optionC.
	 * @param optionC The optionC to set
	 */
	public void setOptionC(String optionC) {
		this.optionC = optionC;
	}

	/** 
	 * Returns the optionB.
	 * @return String
	 */
	public String getOptionB() {
		return optionB;
	}

	/** 
	 * Set the optionB.
	 * @param optionB The optionB to set
	 */
	public void setOptionB(String optionB) {
		this.optionB = optionB;
	}

	/** 
	 * Returns the subjectName.
	 * @return String
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/** 
	 * Set the subjectName.
	 * @param subjectName The subjectName to set
	 */
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	/** 
	 * Returns the optionA.
	 * @return String
	 */
	public String getOptionA() {
		return optionA;
	}

	/** 
	 * Set the optionA.
	 * @param optionA The optionA to set
	 */
	public void setOptionA(String optionA) {
		this.optionA = optionA;
	}

	/** 
	 * Returns the answer.
	 * @return String
	 */
	public String getAnswer() {
		return answer;
	}

	/** 
	 * Set the answer.
	 * @param answer The answer to set
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/** 
	 * Returns the sectionName.
	 * @return String
	 */
	public String getSectionName() {
		return sectionName;
	}

	/** 
	 * Set the sectionName.
	 * @param sectionName The sectionName to set
	 */
	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	/** 
	 * Returns the questionStem.
	 * @return String
	 */
	public String getQuestionStem() {
		return questionStem;
	}

	/** 
	 * Set the questionStem.
	 * @param questionStem The questionStem to set
	 */
	public void setQuestionStem(String questionStem) {
		this.questionStem = questionStem;
	}

	/** 
	 * Returns the analysis.
	 * @return String
	 */
	public String getAnalysis() {
		return analysis;
	}

	/** 
	 * Set the analysis.
	 * @param analysis The analysis to set
	 */
	public void setAnalysis(String analysis) {
		this.analysis = analysis;
	}

	/** 
	 * Returns the optionE.
	 * @return String
	 */
	public String getOptionE() {
		return optionE;
	}

	/** 
	 * Set the optionE.
	 * @param optionE The optionE to set
	 */
	public void setOptionE(String optionE) {
		this.optionE = optionE;
	}
}