/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.forms;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
/**   
 *    
 * 项目名称：ExamHelper   
 * 类名称：SubjectForm  
 * 类描述： 添加subject时使用的表单
 * 创建人：叶睿雯    
 * 创建时间：2014-3-15   
 * 修改人：     
 * 修改时间：   
 * 修改备注：   
 * @version    
 *    
 */ 
public class SubjectForm extends ActionForm {
	
	/*
	 * Generated fields
	 */
	
	/** subName property */
	private String subName;

	/*
	 * Generated Methods
	 */

	

	
	/** 
	 * Returns the subName.
	 * @return String
	 */
	public String getSubName() {
		return subName;
	}

	/** 
	 * Set the subName.
	 * @param subName The subName to set
	 */
	public void setSubName(String subName) {
		this.subName = subName;
	}
}