/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-19-2014
 * 
 * XDoclet definition:
 * @struts.form name="trueOrFalseForm"
 */
public class TrueOrFalseForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** subjectName property */
	private String subjectName;

	/** remark property */
	private String remark;

	/** answer property */
	private String answer;

	/** sectionName property */
	private String sectionName;

	/** questionStem property */
	private String questionStem;

	/** analysis property */
	private String analysis;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the subjectName.
	 * @return String
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/** 
	 * Set the subjectName.
	 * @param subjectName The subjectName to set
	 */
	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	/** 
	 * Returns the remark.
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/** 
	 * Set the remark.
	 * @param remark The remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/** 
	 * Returns the answer.
	 * @return String
	 */
	public String getAnswer() {
		return answer;
	}

	/** 
	 * Set the answer.
	 * @param answer The answer to set
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/** 
	 * Returns the sectionName.
	 * @return String
	 */
	public String getSectionName() {
		return sectionName;
	}

	/** 
	 * Set the sectionName.
	 * @param sectionName The sectionName to set
	 */
	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	/** 
	 * Returns the questionStem.
	 * @return String
	 */
	public String getQuestionStem() {
		return questionStem;
	}

	/** 
	 * Set the questionStem.
	 * @param questionStem The questionStem to set
	 */
	public void setQuestionStem(String questionStem) {
		this.questionStem = questionStem;
	}

	/** 
	 * Returns the analysis.
	 * @return String
	 */
	public String getAnalysis() {
		return analysis;
	}

	/** 
	 * Set the analysis.
	 * @param analysis The analysis to set
	 */
	public void setAnalysis(String analysis) {
		this.analysis = analysis;
	}
}