/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.actions;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yrw.domains.Collection;
import com.yrw.domains.User;
import com.yrw.domains.satatics.Scollection;
import com.yrw.service.CollectionService;
import com.yrw.service.SubjectService;

/**
 * 类名称：CollectionAction 类描述：收藏统计Action 创建人： 张帅 创建时间：2014年4月24日 下午6:38:41
 */
public class CollectionAction extends DispatchAction {

	private CollectionService collectionService;
	private SubjectService subjectService;

	public void setCollectionService(CollectionService collectionService) {
		this.collectionService = collectionService;
	}

	public void setSubjectService(SubjectService subjectService) {
		this.subjectService = subjectService;
	}

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward showCollectionList(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		// int pageNow = 1;
		// int pageCount = userService.getPageCount();
		// String pageNowString = request.getParameter("pageNow");
		// if (pageNowString != null) {
		// pageNow = Integer.parseInt(pageNowString);
		// if (pageNow < 1)
		// pageNow = 1;
		// else if (pageNow > pageCount)
		// pageNow = pageCount;
		// }
		//
		// List<User> userList = userService.getUserListByPage(pageNow);
		// request.setAttribute("userList", userList);
		// request.setAttribute("pageCount", pageCount);
		// request.setAttribute("pageNow", pageNow);
		return mapping.findForward("showCollection");
	}

	
}
