/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.actions;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yrw.service.CollectionService;
import com.yrw.service.ErrorQuestionService;

public class ErrorAction extends DispatchAction {
	private ErrorQuestionService errorQuestionService;

	public void setErrorQuestionService(ErrorQuestionService errorQuestionService) {
		this.errorQuestionService = errorQuestionService;
	}

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward showErrorList(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		int pageNow = 1;
//		int pageCount = errorQuestionService.
//		String pageNowString = request.getParameter("pageNow");
//		if (pageNowString != null) {
//			pageNow = Integer.parseInt(pageNowString);
//			if (pageNow < 1)
//				pageNow = 1;
//			else if (pageNow > pageCount)
//				pageNow = pageCount;
//		}
		return null;
	}
}