/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.actions;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yrw.config.DefaultValue;
import com.yrw.domains.Examination;
import com.yrw.domains.Examsection;
import com.yrw.domains.Materialanalysis;
import com.yrw.domains.Multichoice;
import com.yrw.domains.Questiontype;
import com.yrw.domains.Singlechoice;
import com.yrw.domains.Subject;
import com.yrw.domains.Trueorfalse;
import com.yrw.service.ExamService;
import com.yrw.service.SubjectService;

/**
 * MyEclipse Struts Creation date: 04-21-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action parameter="flag" validate="true"
 */
public class ExaminationAction extends DispatchAction {

	private ExamService examService;
	private SubjectService subjectService;

	public void setSubjectService(SubjectService subjectService) {
		this.subjectService = subjectService;
	}

	public void setExamService(ExamService examService) {
		this.examService = examService;
	}

	/**
	 * 罗列某个科目下的所有试卷
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward showExamList(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int subjectId = (Integer) request.getSession()
				.getAttribute("subjectId");
		System.out.println("Action: showExam" + subjectId);
		String pageNowString = request.getParameter("pageNow");
		List collection = examService
				.listExaminations(pageNowString, subjectId);

		Map<String, Integer> pageMap = (Map<String, Integer>) collection.get(0);
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		request.setAttribute("pageCount", pageMap.get("pageCount"));

		List<Examination> exmaList = (List<Examination>) collection.get(1);
		request.setAttribute("examinations", exmaList);

		request.getSession().setAttribute("subjectId", subjectId);

		return mapping.findForward("showExamList");

	}

	/**
	 * 显示试卷信息及内容
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward showExamination(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// 得到examination对象
		int examinationId = Integer.parseInt(request
				.getParameter("examinationId"));
		Examination examination = examService.getExamination(examinationId);
		// 设置examination在jsp上的对象
		request.setAttribute("examination", examination);
		// 设置examination中科目的下拉框
		List<Subject> subjectList = subjectService.getSubjectList(examination
				.getSubject().getId());
		if (subjectList != null) {
			request.setAttribute("subject", subjectList.get(0));
			subjectList.remove(0);
			request.setAttribute("subjects", subjectList);
		} else
			request.setAttribute("subject", "暂无所属科目");
		// 设置examination下的题型
		List<Examsection> examsections = new ArrayList<Examsection>(
				examination.getExamsections());
		request.setAttribute("examSections", examsections);
		// 设置每个题型下的具体题目
		Questiontype questiontype = null;
		for (int i = 0; i < examsections.size(); i++) {
			questiontype = examsections.get(i).getQuestiontype();
			if (questiontype.getTypeName().equals(DefaultValue.SINGLE_CHOICE)) {
				List<Singlechoice> singlechoices = (List<Singlechoice>) examService
						.getQuestions(examsections.get(i));
				request.setAttribute("singleChoices", singlechoices);
			} else if (questiontype.getTypeName().equals(
					DefaultValue.MULTI_CHOICE)) {
				List<Multichoice> multichoices = (List<Multichoice>) examService
						.getQuestions(examsections.get(i));
				request.setAttribute("multiChoices", multichoices);
			} else if (questiontype.getTypeName().equals(
					DefaultValue.TRUE_OR_FALSE)) {
				List<Trueorfalse> trueorfalses = (List<Trueorfalse>) examService
						.getQuestions(examsections.get(i));
				request.setAttribute("trueOrFalses", trueorfalses);
			} else if (questiontype.getTypeName().equals(
					DefaultValue.MATERIAL_ANALYSIS)) {
				List<Materialanalysis> materialanalysis = (List<Materialanalysis>) examService
						.getQuestions(examsections.get(i));
				request.setAttribute("materialAnalysises", materialanalysis);
			}
		}
		return mapping.findForward("showExamination");
	}

	/**
	 * 修改试卷信息
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward editExaminationInfor(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// 获取jsp页面上的数据
		int examinationId = Integer.parseInt(request
				.getParameter("examinationId"));
		String examName = request.getParameter("examName");
		String subjectName = request.getParameter("subjectName");
		String examType = request.getParameter("examType");
		String examTime = request.getParameter("examTime");
		String examRequest = request.getParameter("examRequest");
		// 获取examination对象
		Examination examination = examService.getExamination(examinationId);
		if (examName != null)
			examination.setExamName(examName);
		if (subjectName != null)
			examination
					.setSubject(subjectService.getSubjectByName(subjectName));
		if (examType != null)
			examination.setExamType(examType);
		if (examTime != null)
			examination.setExamTime(Integer.parseInt(examTime));
		if (examRequest != null)
			examination.setExamRequest(examRequest);
		return mapping.findForward("showExamination");
	}
}