/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.actions;

import java.io.UnsupportedEncodingException;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yrw.config.DefaultValue;
import com.yrw.domains.Multichoice;
import com.yrw.domains.Questiontype;
import com.yrw.domains.Section;
import com.yrw.domains.Subject;
import com.yrw.service.QuestionService;
import com.yrw.service.SectionService;
import com.yrw.service.SubjectService;
import com.yrw.web.forms.MultiChoiceForm;

/**
 * MyEclipse Struts Creation date: 04-17-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/multiChoice" name="multiChoiceForm" parameter="flag"
 *                scope="request" validate="true"
 */
public class MultiChoiceAction extends DispatchAction {
	private QuestionService questionService;
	private SectionService sectionService;
	private SubjectService subjectService;

	public void setQuestionService(QuestionService questionService) {
		this.questionService = questionService;
	}

	public void setSectionService(SectionService sectionService) {
		this.sectionService = sectionService;
	}

	public void setSubjectService(SubjectService subjectService) {
		this.subjectService = subjectService;
	}

	/**
	 * 加载sectionList
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward loadSectionList(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		String subjectString = request.getParameter("subjectId");
		String questionTypeNameString=request.getParameter("questionTypeName");
		int subjectId = 0;
		if (subjectString != null)
			if (subjectString.length() > 0) {
				subjectId = Integer.parseInt(subjectString);
				request.getSession().setAttribute("subjectId", subjectId);
			}
		if(questionTypeNameString!=null)
			if(questionTypeNameString.length()>0&&!questionTypeNameString.equals("null"))
				request.setAttribute("questionTypeName", questionTypeNameString);
		
		
		List<Section> sections = sectionService.listSectionBySubject(subjectId);
		request.setAttribute("sections", sections);

		List<Subject> subjects = subjectService.getSubjects();
		List<Questiontype> questiontypes = questionService.showQuestiontypes();
		request.setAttribute("subjects", subjects);
		request.setAttribute("questionTypes", questiontypes);

		return mapping.findForward("showMultiChoiceList");
	}

	/**
	 * Method showQuestionBySection 按题目章节
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws UnsupportedEncodingException
	 */
	public ActionForward showMultiChoiceList(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws UnsupportedEncodingException {
		// TODO Auto-generated method stub
		// 加载章节类型
		String sectionName = new String(request.getParameter("sectionName")
				.getBytes("ISO-8859-1"), "utf-8");

		String typeName = DefaultValue.MULTI_CHOICE;
		Section existSection = sectionService
				.getSectionBySectionName(sectionName);
		String pageNowString = request.getParameter("pageNow");

		// 加载科目
		int subjectId = existSection.getSubject().getId();
		request.getSession().setAttribute("subjectId", subjectId);
		request.setAttribute("subjects", subjectService.getSubjects());

		// 加载问题类型
		List<Questiontype> questiontypes = questionService.showQuestiontypes();
		request.setAttribute("questionTypeName", typeName);
		request.setAttribute("questionTypes", questiontypes);

		// 为jsp中的section设置值
		request.setAttribute("sectionName", sectionName);
		request.setAttribute("sections",
				sectionService.listSectionBySubject(subjectId));
		// 加载章节下的题目
		List collection = questionService.listQuestionBySection(
				existSection.getId(), pageNowString, typeName);

		Map<String, Integer> pageMap = (Map<String, Integer>) collection.get(0);
		request.setAttribute("pageCount", pageMap.get("pageCount"));
		request.setAttribute("pageNow", pageMap.get("pageNow"));

		// 设置问题

		if (typeName.equals(DefaultValue.MULTI_CHOICE))

			request.setAttribute("multiChoices", (List) collection.get(1));

		return mapping.findForward((String) collection.get(2));
	}

	/**
	 * 显示多项选择详情
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward showMultiChoice(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		int multiChoiceId = Integer.parseInt(request
				.getParameter("multiChoiceId"));
		Multichoice multichoice = (Multichoice) questionService.getQuestion(
				multiChoiceId, DefaultValue.MULTI_CHOICE);
		request.setAttribute("multiChoice", multichoice);

		// 获得subject下拉菜单里的所有subject
		request.setAttribute("subject", multichoice.getSection().getSubject()
				.getSubName());
		// 获得下拉菜单里的所有section
		request.setAttribute("sectionName", multichoice.getSection()
				.getSectionName());
		return mapping.findForward("showMultiChoice");
	}

	/**
	 * 编辑多项选择题
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward editMultiChoice(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		int multiChoiceId = Integer.parseInt(request
				.getParameter("multiChoiceId"));
		Multichoice multichoice = (Multichoice) questionService.getQuestion(
				multiChoiceId, DefaultValue.MULTI_CHOICE);
		request.setAttribute("multiChoice", multichoice);

		String pageNowString = request.getParameter("pageNow");
		if (pageNowString != null)
			if (pageNowString.length() > 0)
				request.setAttribute("pageNow", Integer.parseInt(pageNowString));

		// 获得subject下拉菜单里的所有subject
		int subjectId = (Integer) request.getSession()
				.getAttribute("subjectId");
		List<Subject> subjectList = subjectService.getSubjects();
		if (subjectList != null) {
			request.setAttribute("subjects", subjectList);
		}

		// 获得下拉菜单里的所有section

		List<Section> sectionList = sectionService
				.listSectionBySubject(subjectId);
		if (sectionList != null) {
			request.setAttribute("sectionName", multichoice.getSection()
					.getSectionName());
			request.setAttribute("sections", sectionList);
		}

		return mapping.findForward("editMultiChoice");
	}

	/**
	 * 保存多项选择题
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws UnsupportedEncodingException
	 */
	public ActionForward saveMultiChoice(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws UnsupportedEncodingException {

		// 存储更改后的多项选择题
		MultiChoiceForm multiChoiceForm = (MultiChoiceForm) form;
		int multiChoiceId = Integer.parseInt(request
				.getParameter("multiChoiceId"));

		Multichoice multichoice = (Multichoice) questionService.getQuestion(
				multiChoiceId, DefaultValue.MULTI_CHOICE);

		multichoice.setQuestionStem(multiChoiceForm.getQuestionStem());
		multichoice.setOptionA(multiChoiceForm.getOptionA());
		multichoice.setOptionB(multiChoiceForm.getOptionB());
		multichoice.setOptionC(multiChoiceForm.getOptionC());
		multichoice.setOptionD(multiChoiceForm.getOptionD());
		multichoice.setOptionE(multiChoiceForm.getOptionE());
		multichoice.setOptionF(multiChoiceForm.getOptionF());
		multichoice.setAnalysis(multiChoiceForm.getAnalysis());

		if (multiChoiceForm.getAnswerA() != null)
			multichoice.setAnswerA(true);
		else
			multichoice.setAnswerA(false);
		if (multiChoiceForm.getAnswerB() != null)
			multichoice.setAnswerB(true);
		else
			multichoice.setAnswerB(false);
		if (multiChoiceForm.getAnswerC() != null)
			multichoice.setAnswerC(true);
		else
			multichoice.setAnswerC(false);
		if (multiChoiceForm.getAnswerD() != null)
			multichoice.setAnswerD(true);
		else
			multichoice.setAnswerD(false);
		if (multiChoiceForm.getAnswerE() != null)
			multichoice.setAnswerE(true);
		else
			multichoice.setAnswerE(false);
		if (multiChoiceForm.getAnswerF() != null)
			multichoice.setAnswerF(true);
		else
			multichoice.setAnswerF(false);

		multichoice.setRemark(multiChoiceForm.getRemark());

		if (multiChoiceForm.getSectionName() != null) {
			Section section = sectionService
					.getSectionBySectionName(multiChoiceForm.getSectionName());
			multichoice.setSection(section);
		}

		questionService.updateMultiChoice(multichoice);

		// 获得subject下拉菜单里的所有subject
		int subjectId = (Integer) request.getSession()
				.getAttribute("subjectId");
		List<Subject> subjectList = subjectService.getSubjects();
		if (subjectList != null) {
			request.setAttribute("subjects", subjectList);
		}
		// 设置section下拉菜单
		request.setAttribute("sectionName", multichoice.getSection()
				.getSectionName());
		List<Section> sections = sectionService.listSectionBySubject(subjectId);
		request.setAttribute("sections", sections);
		// 设置科目列表
		request.setAttribute("subjects", subjectService.getSubjects());
		// 设置题型
		request.setAttribute("questionTypeName", DefaultValue.MULTI_CHOICE);
		request.setAttribute("questionTypes",
				questionService.showQuestiontypes());
		// 设置题目及页码
		List collection = questionService.listQuestionBySection(multichoice
				.getSection().getId(), null,
				DefaultValue.MULTI_CHOICE);
		// 设置页码
		Map<String, Integer> pageMap = (Map<String, Integer>) collection.get(0);
		request.setAttribute("pageCount", pageMap.get("pageCount"));
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		// 设置单项选择题
		request.setAttribute("multiChoices",
				(List<Multichoice>) collection.get(1));
		return mapping.findForward("showMultiChoiceList");

	}

	/**
	 * Method addMultiChoiceUI 跳转到添加多选题的UI界面
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward addMultiChoiceUI(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		String pageNowString = request.getParameter("pageNow");
		if (pageNowString != null)
			if (pageNowString.length() > 0)
				request.setAttribute("pageNow", Integer.parseInt(pageNowString));
	
		int subjectId = (Integer) request.getSession()
				.getAttribute("subjectId");
		List<Section> sectionList = sectionService
				.listSectionBySubject(subjectId);
		List<Subject> subjectList = subjectService.getSubjects();
		request.setAttribute("subjects", subjectList);
		request.setAttribute("sections", sectionList);
		return mapping.findForward("addMultiChoice");
	}

	/**
	 * Method addMultiChoice 添加多选题
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws UnsupportedEncodingException
	 */
	public ActionForward addMultiChoice(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws UnsupportedEncodingException {

		MultiChoiceForm multiChoiceForm = (MultiChoiceForm) form;
		Multichoice multichoice = new Multichoice();
		multichoice.setQuestionStem(multiChoiceForm.getQuestionStem());
		multichoice.setOptionA(multiChoiceForm.getOptionA());
		multichoice.setOptionB(multiChoiceForm.getOptionB());
		multichoice.setOptionC(multiChoiceForm.getOptionC());
		multichoice.setOptionD(multiChoiceForm.getOptionD());
		multichoice.setOptionE(multiChoiceForm.getOptionE());
		multichoice.setOptionF(multiChoiceForm.getOptionF());
		if (multiChoiceForm.getAnswerA() != null)
			multichoice.setAnswerA(true);
		else
			multichoice.setAnswerA(false);
		if (multiChoiceForm.getAnswerB() != null)
			multichoice.setAnswerB(true);
		else
			multichoice.setAnswerB(false);
		if (multiChoiceForm.getAnswerC() != null)
			multichoice.setAnswerC(true);
		else
			multichoice.setAnswerC(false);
		if (multiChoiceForm.getAnswerD() != null)
			multichoice.setAnswerD(true);
		else
			multichoice.setAnswerD(false);
		if (multiChoiceForm.getAnswerE() != null)
			multichoice.setAnswerE(true);
		else
			multichoice.setAnswerE(false);
		if (multiChoiceForm.getAnswerF() != null)
			multichoice.setAnswerF(true);
		else
			multichoice.setAnswerF(false);

		multichoice.setRemark(multiChoiceForm.getRemark());

		if (multiChoiceForm.getSectionName() != null) {
			Section section = sectionService
					.getSectionBySectionName(multiChoiceForm.getSectionName());
			multichoice.setSection(section);
			
			request.getSession().setAttribute("subjectId",
					section.getSubject().getId());
		} else {
			multichoice.setSection(null);

		}
		questionService.addMultiChoice(multichoice);
		
		// 设置subject下拉菜单
		request.setAttribute("subjects", subjectService.getSubjects());
		// 设置在section下拉列表
		request.setAttribute("sectionName", multichoice.getSection()
				.getSectionName());
		List<Section> sections = sectionService
				.listSectionBySubject(multichoice.getSection().getSubject()
						.getId());
		request.setAttribute("sections", sections);
		// 设置问题类型下拉菜单
		request.setAttribute("questionTypeName", DefaultValue.MULTI_CHOICE);
		request.setAttribute("questionTypes",
				questionService.showQuestiontypes());
		// 设置题目及页码

		List collection = questionService.listQuestionBySection(multichoice
				.getSection().getId(), null, DefaultValue.MULTI_CHOICE);
		// 设置页码
		Map<String, Integer> pageMap = (Map<String, Integer>) collection.get(0);
		request.setAttribute("pageCount", pageMap.get("pageCount"));
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		// 设置单项选择题
		request.setAttribute("multichoices",
				(List<Multichoice>) collection.get(1));
		return mapping.findForward("showMultiChoiceList");
	}

	/**
	 * 删除多选题
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 * @throws UnsupportedEncodingException
	 */
	public ActionForward deleteMultiChoice(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws UnsupportedEncodingException {
		int multiChoiceId = Integer.parseInt(request
				.getParameter("multiChoiceId"));
		Multichoice multichoice = (Multichoice) questionService.getQuestion(
				multiChoiceId, DefaultValue.MULTI_CHOICE);
		// 设置section下拉框
		request.setAttribute("sectionName", multichoice.getSection()
				.getSectionName());
		request.setAttribute(
				"sections",
				sectionService.listSectionBySubject(multichoice.getSection()
						.getSubject().getId()));
		// 设置subject下拉框
		request.setAttribute("subjects", subjectService.getSubjects());
		// 设置questionType下拉框
		request.setAttribute("questionTypeName", DefaultValue.MULTI_CHOICE);
		request.setAttribute("questionTypes",
				questionService.showQuestiontypes());

		// 删除该选择题
		questionService
				.deleteQuestion(DefaultValue.MULTI_CHOICE, multichoice);

		// 设置页码及问题
		String pageNowString = request.getParameter("pageNow");
		List collection = questionService.listQuestionBySection(multichoice
				.getSection().getId(), pageNowString,
				DefaultValue.MULTI_CHOICE);
		// 设置页码
		Map<String, Integer> pageMap = (Map<String, Integer>) collection.get(0);
		request.setAttribute("pageCount", pageMap.get("pageCount"));
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		// 设置单项选择题
		request.setAttribute("multiChoices",
				(List<Multichoice>) collection.get(1));

		return mapping.findForward("showMultiChoiceList");

	}
}