/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.actions;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yrw.service.AdImagesService;

public class SquareAdAction extends DispatchAction {
	private AdImagesService adImagesService;

	public void setAdImagesService(AdImagesService adImagesService) {
		this.adImagesService = adImagesService;
	}

	/**
	 * Method execute
	 * 展示当前客户端广告
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward showNowAd(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		List<String> adImageUrlList = adImagesService.getAdImageUrlListByTime();
		request.setAttribute("adImageUrlList", adImageUrlList);
		return mapping.findForward("squareAd");
	}
}