/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.actions;

import java.io.UnsupportedEncodingException;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yrw.domains.Section;
import com.yrw.domains.Subject;
import com.yrw.service.SectionService;
import com.yrw.service.SubjectService;
import com.yrw.web.forms.SubjectForm;

/**
 * 
 * 项目名称：ExamHelper 类名称：SubjectAction 类描述： 跟科目操作有关的分派action 创建人：叶睿雯
 * 创建时间：2014-3-15 修改人： 修改时间： 修改备注：
 * 
 * @version
 * 
 */
public class SubjectAction extends DispatchAction {

	private SubjectService subjectService;
	private SectionService sectionService;

	public void setSectionService(SectionService sectionService) {
		this.sectionService = sectionService;
	}

	public void setSubjectService(SubjectService subjectService) {
		this.subjectService = subjectService;
	}

	/**
	 * 显示所有科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward listSubject(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub

		String pageNowString = request.getParameter("pageNow");
		List collection = subjectService.listSubject(pageNowString);
		Map<String, Integer> pageMap = (Map<String, Integer>) collection.get(0);
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		request.setAttribute("pageCount", pageMap.get("pageCount"));
		request.setAttribute("subjects", collection.get(1));
		return mapping.findForward("listSubject");

	}

	/**
	 * 删除科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward deleteSubject(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String subjectIdString = request.getParameter("subjectId");
		System.out.println("deleteSubjcet");
		try {
			subjectService.deleteSubject(Integer.parseInt(subjectIdString));
		} catch (Exception e) {
			// TODO: handle exception
			mapping.findForward("fail");
		}

		return listSubject(mapping, form, request, response);

	}

	/**
	 * 批量删除科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward delSubjectByList(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		String idString = (String) request.getParameter("paramsHidden");

		String[] ids = idString.substring(9).split("delid");
		String id = "*";

		for (int i = 1; i < ids.length; i++) {

			if (i == ids.length - 1)
				id = id + ids[i];
			else
				id = id + ids[i] + ",";

		}
		subjectService.delSubjectByList(id.substring(1));
		request.setAttribute("pageNow", request.getParameter("pageNow"));
		return listSubject(mapping, null, request, response);

	}

	/**
	 * 跳转到创建新subject的表格jsp
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws UnsupportedEncodingException 
	 */
	public ActionForward addSubjectUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		
		if(request.getParameter("sectionInfor")!=null){
			String section =new String(request.getParameter("sectionInfor").getBytes(
					"ISO-8859-1"), "utf-8");
			request.setAttribute("section", section);
		}
		
		
		
	
		return mapping.findForward("addSubject");
	}

	/**
	 * 创建新科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward addSubject(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SubjectForm subjectForm = (SubjectForm) form;
		Subject subject = new Subject();
		subject.setSubName(subjectForm.getSubName());
	
		if(subjectService.addSubject(subject)){

		String sectionString = (String) request.getParameter("paramsHidden");
		System.out.println(sectionString);
		//判断添加科目的请求来自于更新section的页面还是showSubje页面
		if (sectionString != null&& !sectionString.equals("/")) {
			
			String sectionInfor[]=sectionString.split(",|/");
			int sectionId= Integer.parseInt(sectionInfor[1]);
			String sectionName=sectionInfor[0];
			Section existsection=sectionService.showSection(sectionId);
			existsection.setSectionName(sectionName);
	
			List<Subject> subjectList=subjectService.getSubjectList(existsection.getSubject().getId());
			
			request.setAttribute("section", existsection);
			request.setAttribute("subject", subjectList.get(0));
			subjectList.remove(0);
			request.setAttribute("subjects", subjectList);
			return mapping.findForward("updateSectionUI");
			}
		else
			return listSubject(mapping, form, request, response);
		}else 
			 {
			request.setAttribute("message", "该科目已存在请重新输入新科目！");
			return mapping.findForward("fail");
		}
			
	}

	/**
	 * 修改科目的界面跳转
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward updateSubjectUI(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		int subjectId = Integer.parseInt(request.getParameter("subjectId"));
		Subject subject = subjectService.getSubjectById(subjectId);
		request.setAttribute("subject", subject);
		return mapping.findForward("updateSubject");
	}

	/**
	 * 修改新科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward updateSubject(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SubjectForm subjectForm = (SubjectForm) form;
		int subjectId = Integer.parseInt(request.getParameter("subjectId"));
		Subject subject = subjectService.getSubjectById(subjectId);
		subject.setSubName(subjectForm.getSubName());
		subjectService.updateSubject(subject);
		return listSubject(mapping, form, request, response);
	}

	/**
	 * 关键字查找对象
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward searchSubjectByKeyWord(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		String pageNowString = request.getParameter("pageNow");
		String keyword = request.getParameter("textfield");

		List collection = subjectService.searchSubjectByKeyWord(keyword,
				pageNowString);

		Map<String, Integer> pageMap = (Map<String, Integer>) collection.get(0);

		request.setAttribute("pageCount", pageMap.get("pageCount"));
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		request.setAttribute("keyword", keyword);

		request.setAttribute("subjects", collection.get(1));
		return mapping.findForward("listSubject");

	}
}