/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.actions;

import java.io.UnsupportedEncodingException;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yrw.domains.Section;
import com.yrw.domains.Subject;
import com.yrw.service.SectionService;
import com.yrw.service.SubjectService;
import com.yrw.web.forms.SubjectForm;

/**
 * 
 * 项目名称：ExamHelper 类名称：SubjectAction 类描述： 跟科目操作有关的分派action 创建人：叶睿雯
 * 创建时间：2014-3-15 修改人： 修改时间： 修改备注：
 * 
 * @version
 * 
 */
public class SubjectAction extends DispatchAction {

	private SubjectService subjectService;
	private SectionService sectionService;

	public void setSectionService(SectionService sectionService) {
		this.sectionService = sectionService;
	}

	public void setSubjectService(SubjectService subjectService) {
		this.subjectService = subjectService;
	}

	/**
	 * 显示所有科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward listSubject(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub

		String pageNowString = request.getParameter("pageNow");
		List collection = subjectService.listSubject(pageNowString);
		Map<String, Integer> pageMap = (Map<String, Integer>) collection.get(0);
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		request.setAttribute("pageCount", pageMap.get("pageCount"));
		request.setAttribute("subjects", collection.get(1));
		return mapping.findForward("listSubject");

	}

	/**
	 * 删除科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward deleteSubject(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		String subjectIdString = request.getParameter("subjectId");
		try {
			subjectService.deleteSubject(Integer.parseInt(subjectIdString));
		} catch (Exception e) {
			// TODO: handle exception
			mapping.findForward("fail");
		}
		// 设置页码
		String pageNowString = request.getParameter("pageNow");
		Map<String, Integer> pageMap = subjectService.getPageMap(pageNowString);
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		request.setAttribute("pageCount", pageMap.get("pageCount"));
		// 设置subjects
		List<Subject> subjects = subjectService.getSubjects(pageMap.get("pageNow"));
		request.setAttribute("subjects", subjects);

		return mapping.findForward("listSubject");
	}

	/**
	 * 批量删除科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward delSubjectByList(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		String idString = (String) request.getParameter("subjectList");

		if (idString != null)
			if (idString.length() > 0)
				subjectService.delSubjectByList(idString);

		// 设置页码
		String pageNowString = request.getParameter("pageNow");
		Map<String, Integer> pageMap = subjectService.getPageMap(pageNowString);
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		request.setAttribute("pageCount", pageMap.get("pageCount"));
		// 设置subjects
		List<Subject> subjects = subjectService.getSubjects(pageMap.get("pageNow"));
		request.setAttribute("subjects", subjects);

		return mapping.findForward("listSubject");

	}

	/**
	 * 跳转到创建新subject的表格jsp
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws UnsupportedEncodingException
	 */
	public ActionForward addSubjectUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws UnsupportedEncodingException {

		request.setAttribute("pageNow", request.getParameter("pageNow"));
		return mapping.findForward("addSubject");
	}

	/**
	 * 创建新科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward addSubject(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SubjectForm subjectForm = (SubjectForm) form;
		Subject subject = new Subject();
		subject.setSubName(subjectForm.getSubName());

		if(subjectService.addSubject(subject))
		{
			// 设置页码
			String pageNowString = request.getParameter("pageNow");
			Map<String, Integer> pageMap = subjectService.getPageMap(pageNowString);
			request.setAttribute("pageNow", pageMap.get("pageNow"));
			request.setAttribute("pageCount", pageMap.get("pageCount"));
			// 设置subjects
			List<Subject> subjects = subjectService.getSubjects(pageMap.get("pageNow"));
			request.setAttribute("subjects", subjects);

			return mapping.findForward("listSubject");
			
		}else {
			return mapping.findForward("fail");
		}

	}

	/**
	 * 修改科目的界面跳转
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward updateSubjectUI(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		int subjectId = Integer.parseInt(request.getParameter("subjectId"));
		Subject subject = subjectService.getSubjectById(subjectId);
		request.setAttribute("pageNow", request.getParameter("pageNow"));
		request.setAttribute("subject", subject);
		return mapping.findForward("updateSubject");
	}

	/**
	 * 修改新科目
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward updateSubject(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SubjectForm subjectForm = (SubjectForm) form;
		int subjectId = Integer.parseInt(request.getParameter("subjectId"));
		Subject subject = subjectService.getSubjectById(subjectId);
		subject.setSubName(subjectForm.getSubName());
		subjectService.updateSubject(subject);

		// 设置页码
		String pageNowString = request.getParameter("pageNow");
		Map<String, Integer> pageMap = subjectService.getPageMap(pageNowString);
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		request.setAttribute("pageCount", pageMap.get("pageCount"));
		// 设置subjects
		List<Subject> subjects = subjectService.getSubjects(pageMap.get("pageNow"));
		request.setAttribute("subjects", subjects);

		return mapping.findForward("listSubject");
	}

	/**
	 * 关键字查找对象
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward searchSubjectByKeyWord(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {

		String pageNowString = request.getParameter("pageNow");
		String keyword = request.getParameter("textfield");

		List collection = subjectService.searchSubjectByKeyWord(keyword,
				pageNowString);

		Map<String, Integer> pageMap = (Map<String, Integer>) collection.get(0);

		request.setAttribute("pageCount", pageMap.get("pageCount"));
		request.setAttribute("pageNow", pageMap.get("pageNow"));
		request.setAttribute("keyword", keyword);

		request.setAttribute("subjects", collection.get(1));
		return mapping.findForward("listSubject");

	}
}