/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.actions;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yrw.domains.Serrorquestions;
import com.yrw.domains.Subject;
import com.yrw.service.SystemNoticeService;

public class SystemNoticeAction extends DispatchAction {
	private SystemNoticeService systemNoticeService;

	public void setSystemNoticeService(SystemNoticeService systemNoticeService) {
		this.systemNoticeService = systemNoticeService;
	}

//	public ActionForward showNoticeList(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response) {
//		// TODO Auto-generated method stub
//		int pageNow = 1;
//		int pageCount = errorQuestionService.getSErrorQuestionPageCount();
//		String pageNowString = request.getParameter("pageNow");
//		if (pageNowString != null) {
//			pageNow = Integer.parseInt(pageNowString);
//			if (pageNow < 1)
//				pageNow = 1;
//			else if (pageNow > pageCount)
//				pageNow = pageCount;
//		}
//
//		List<String> questionStemList = new ArrayList<String>();
//		List<Serrorquestions> serrorquestionList = errorQuestionService.getSErrorQuestionListByPageNow(pageNow);
//		for (Serrorquestions serrorquestions : serrorquestionList) {
//			questionStemList.add(getQuestionName(serrorquestions.getQuestionId(), serrorquestions.getQuestiontype()
//					.getTypeName()));
//		}
//		
//		List<Subject> subjectList = subjectService.getSubjects();
//
//		request.setAttribute("serrorquestionList", serrorquestionList);
//		request.setAttribute("questionStemList", questionStemList);
//		request.setAttribute("subjectList", subjectList);
//		request.setAttribute("pageCount", pageCount);
//		request.setAttribute("pageNow", pageNow);
//		return mapping.findForward("showNoticeList");
//	}
}