/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yrw.web.actions;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.yrw.domains.User;
import com.yrw.service.UserService;

public class UserAction extends DispatchAction {
	private UserService userService;

	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward showUserList(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		// TODO Auto-generated method stub
		int pageNow = 1;
		int pageCount = userService.getPageCount();
		String pageNowString = request.getParameter("pageNow");
		if (pageNowString != null) {
			pageNow = Integer.parseInt(pageNowString);
			if (pageNow < 1)
				pageNow = 1;
			else if (pageNow > pageCount)
				pageNow = pageCount;
		}

		List<User> userList = userService.getUserListByPage(pageNow);
		request.setAttribute("userList", userList);
		request.setAttribute("pageCount", pageCount);
		request.setAttribute("pageNow", pageNow);
		return mapping.findForward("userInfo");
	}

	/**
	 * 删除用户
	 */
	public ActionForward deleteUser(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		String userIdString = request.getParameter("userId");
		int userId = 0;
		if (userIdString != null) {
			userId = Integer.parseInt(request.getParameter("userId"));
		}

		int pageNow = 1;
		int pageCount = userService.getPageCount();
		String pageNowString = request.getParameter("pageNow");
		if (pageNowString != null) {
			pageNow = Integer.parseInt(pageNowString);
			if (pageNow < 1)
				pageNow = 1;
			else if (pageNow > pageCount)
				pageNow = pageCount;
		}
		if (userId > 0) {
			userService.deleteUser(userId);
		}

		List<User> userList = userService.getUserListByPage(pageNow);
		request.setAttribute("userList", userList);
		request.setAttribute("pageCount", pageCount);
		request.setAttribute("pageNow", pageNow);
		return mapping.findForward("userInfo");
	}

	/**
	 * 查找用户
	 */
	public ActionForward searchUser(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) throws Exception {
		// TODO Auto-generated method stub
		String type = new String(request.getParameter("type").getBytes("ISO-8859-1"), "utf-8");
		String content = new String(request.getParameter("content").getBytes("ISO-8859-1"), "utf-8");
		List<User> userList = new ArrayList<User>();
		int pageNow = 1;
		int pageCount = 1;

		if (type != null) {
			if (type.equals("按邮箱")) {
				userList = userService.getUserListByMail(content);
			} else if (type.equals("按昵称")) {
				userList = userService.getUserListByNickName(content);
			}
		}

		request.setAttribute("userList", userList);
		request.setAttribute("pageCount", pageCount);
		request.setAttribute("pageNow", pageNow);
		return mapping.findForward("userInfo");
	}

}